### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by karellm**
This really confused me at first but the documentation is wrong and the code used 2 different options names. This fixes it all.

### CODE REVIEW

**Comment by lpender** [comment]
This was fixed in another PR

**Comment by lpender** [comment]
https://github.com/lpender/gulp-cloudfront-invalidate-aws-publish/pull/12

**Comment by lpender** [comment]
Thanks, I haven't used this option, I think I copy/pasted it from somewhere.

**Comment by karellm** [comment]
My bad, I didn't look at open PRs. Thanks for merging this!

**Pull request closed without merging**
